{ config, pkgs, lib, stateVersion, ... }:
let
  cfg = "${config.home.homeDirectory}/.dot_files_nixos/config";
in
{
  imports = [
    ./programs/zsh.nix
    ./programs/neovim.nix
    ./programs/tmux.nix
    ./programs/git.nix
    ./packages-debian.nix
    ./services/syncthing.nix
  ];

  # Required on non-NixOS distros: patches a few assumptions (fonts, XDG dirs) that
  # Home Manager otherwise takes for granted from the NixOS module system.
  targets.genericLinux.enable = true;

  home.username = "mauro";
  home.homeDirectory = "/home/mauro";
  # Do NOT change this after the initial install — it controls the Home Manager state schema version.
  home.stateVersion = stateVersion;

  xdg.enable = true;

  # Clones or fast-forwards private sibling repos at every `home-manager switch`.
  home.activation.syncPrivate = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    export GIT_SSH_COMMAND="${pkgs.openssh}/bin/ssh -i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new -o BatchMode=yes"
    sync() {
      local repo=$1 dest=$2
      if [ ! -d "$dest" ]; then
        $DRY_RUN_CMD ${pkgs.git}/bin/git clone "git@github.com:crivotz/$repo.git" "$dest"
      else
        $DRY_RUN_CMD ${pkgs.git}/bin/git -C "$dest" pull --ff-only --quiet || true
      fi
    }
    sync nubem_dot_files "$HOME/.nubem_dot_files"
    sync nv-ide          "$HOME/.nv-ide"
    sync gcheck          "$HOME/.gcheck"
    if [ ! -L "$HOME/.config/nvim" ]; then
      $DRY_RUN_CMD rm -rf "$HOME/.config/nvim"
      $DRY_RUN_CMD ln -s "$HOME/.nv-ide" "$HOME/.config/nvim"
    fi
    if [ ! -L "$HOME/.config/tmuxp" ]; then
      $DRY_RUN_CMD rm -rf "$HOME/.config/tmuxp"
      $DRY_RUN_CMD ln -s "$HOME/.nubem_dot_files/tmuxp" "$HOME/.config/tmuxp"
    fi
    if [ ! -L "$HOME/.config/gcheck" ]; then
      $DRY_RUN_CMD rm -rf "$HOME/.config/gcheck"
      $DRY_RUN_CMD ln -s "$HOME/.nubem_dot_files/gcheck" "$HOME/.config/gcheck"
    fi
    $DRY_RUN_CMD mkdir -p "$HOME/.local/bin"
    if [ ! -L "$HOME/.local/bin/gcheck" ]; then
      $DRY_RUN_CMD ln -sf "$HOME/.gcheck/gcheck.sh" "$HOME/.local/bin/gcheck"
    fi
  '';

  home.file = {
    # Powerlevel10k prompt config (generated by `p10k configure`) — same file as NIXMAU/NIXMAULT.
    ".p10k.zsh".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/p10k.zsh";
    # Lazygit UI config
    ".config/lazygit/config.yml" = { source = config.lib.file.mkOutOfStoreSymlink "${cfg}/lazygit/config.yml"; force = true; };
    # Eza column/icon theme config
    ".config/eza".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/eza";
    # Bat custom syntax-highlighting themes (must run `bat cache --build` after changes)
    ".config/bat/themes".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/bat/themes";
    # Claude Code settings (theme, statusLine) and statusline script
    ".claude/settings.json" = { source = config.lib.file.mkOutOfStoreSymlink "${cfg}/claude/settings.json"; force = true; };
    ".claude/statusline.sh" = { source = config.lib.file.mkOutOfStoreSymlink "${cfg}/claude/statusline.sh"; force = true; };
    # Ruby: IRB config, gem defaults, and rbenv default-gems/npm-packages lists
    ".irbrc".source                = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/irbrc";
    ".gemrc".source                = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/gemrc";
    ".default-gems".source         = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/default-gems";
    ".default-npm-packages".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/default-npm-packages";
    # Private git config, shell aliases, and env vars (sourced from nubem_dot_files cloned by the activation above)
    # NOTE: gitconfig_debian must exist in the nubem_dot_files repo — create it there before first switch.
    ".gitconfig".source      = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nubem_dot_files/gitconfig_debian";
    ".zsh_aliases".source    = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nubem_dot_files/zsh_aliases";
    ".nubem_env".source      = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nubem_dot_files/nubem_env";
    # ~/.config/nvim, ~/.config/tmuxp and ~/.config/gcheck symlinks are created by the activation script above
  };

  programs.direnv = {
    enable = true;
    enableZshIntegration = true;
    nix-direnv.enable = true;
  };

  # Allows `home-manager` CLI to manage itself without a NixOS integration.
  programs.home-manager.enable = true;
}
