{ config, pkgs, lib, stateVersion, ... }:
let
  cfg = "${config.home.homeDirectory}/.dot_files_nixos/config";
in
{
  imports = [
    ./programs/zsh.nix
    ./programs/neovim.nix
    ./programs/tmux.nix
    ./programs/git.nix
    ./programs/sway-desktop.nix
    ./packages.nix
    ./services/syncthing.nix
  ];

  home.username = "mauro";
  home.homeDirectory = "/home/mauro";
  # Do NOT change this after the initial install — it controls the Home Manager state schema version.
  home.stateVersion = stateVersion;

  # Creates XDG_DATA_HOME, XDG_CONFIG_HOME, etc. and sets the corresponding env vars.
  xdg.enable = true;

  # Clones or fast-forwards private sibling repos at every `nixos-rebuild switch`.
  # GIT_CONFIG_COUNT overrides git config inline so gh auth is used without touching ~/.gitconfig.
  # url.insteadOf rewrites ssh:// to https:// so the clone works without an SSH agent.
  home.activation.syncPrivate = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    export GIT_CONFIG_COUNT=2
    export GIT_CONFIG_KEY_0="credential.helper"
    export GIT_CONFIG_VALUE_0="${pkgs.gh}/bin/gh auth git-credential"
    export GIT_CONFIG_KEY_1="url.https://github.com/.insteadOf"
    export GIT_CONFIG_VALUE_1="git@github.com:"
    sync() {
      local repo=$1 dest=$2
      if [ ! -d "$dest" ]; then
        $DRY_RUN_CMD ${pkgs.git}/bin/git clone "https://github.com/crivotz/$repo.git" "$dest"
      else
        $DRY_RUN_CMD ${pkgs.git}/bin/git -C "$dest" pull --ff-only --quiet || true
      fi
    }
    sync nubem_dot_files "$HOME/.nubem_dot_files"
    sync nv-ide          "$HOME/.nv-ide"
    if [ ! -e "$HOME/.config/nvim" ]; then
      $DRY_RUN_CMD ln -s "$HOME/.nv-ide" "$HOME/.config/nvim"
    fi
  '';

  # All entries use mkOutOfStoreSymlink so the files are mutable live-links into the
  # sibling dot_files repo rather than read-only copies in the Nix store.
  # `force = true` allows overwriting a pre-existing file or directory at the target path.
  home.file = {
    # Powerlevel10k prompt config (generated by `p10k configure`)
    ".p10k.zsh".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/p10k.zsh";
    # Ghostty terminal config and custom shaders
    ".config/ghostty/config".source  = config.lib.file.mkOutOfStoreSymlink "${cfg}/ghostty/config";
    ".config/ghostty/shaders".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/ghostty/shaders";
    # Eza column/icon theme config
    ".config/eza".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/eza";
    # Lazygit UI config
    ".config/lazygit/config.yml" = { source = config.lib.file.mkOutOfStoreSymlink "${cfg}/lazygit/config.yml"; force = true; };
    # Bat custom syntax-highlighting themes (must run `bat cache --build` after changes)
    ".config/bat/themes".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/bat/themes";
    # Ruby: IRB config, gem defaults, and rbenv default-gems/npm-packages lists
    ".irbrc".source          = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/irbrc";
    ".gemrc".source          = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/gemrc";
    ".default-gems".source   = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/default-gems";
    ".default-npm-packages".source = config.lib.file.mkOutOfStoreSymlink "${cfg}/ruby/default-npm-packages";
    # Private git config (desktop variant — gitconfig_7040), shell aliases, and env vars
    ".gitconfig".source      = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nubem_dot_files/gitconfig_7040";
    ".zsh_aliases".source    = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nubem_dot_files/zsh_aliases";
    ".nubem_env".source      = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nubem_dot_files/nubem_env";
    # Tmuxp session layouts (named sessions for common projects)
    ".config/tmuxp".source   = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/.nubem_dot_files/tmuxp";
  };

  # Automatically loads/unloads the Nix dev environment defined in .envrc when entering a project dir.
  # nix-direnv caches the shell so switching directories is instant rather than re-evaluating the flake.
  programs.direnv = {
    enable = true;
    enableZshIntegration = true;
    nix-direnv.enable = true;
  };

  # Allows `home-manager` CLI to manage itself without a NixOS integration.
  programs.home-manager.enable = true;
}
